config/routes.rb
Rails.application.routes.draw do
  #use custom registrations controller
  devise_for :users, path: "/", path_names: {sign_in: "login", sign_up: "signup"}, controllers: {:registrations => "registrations"}

  root to: "pages#index"
  # get "/", to: "pages#index", as: "root"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  #extra information for printers to enter:
  get "/printer_info", to: "pages#printer_info", as: "printer_info"
  # get "/printers", to: "pages#printers", as: "printers"

  post "/printer_info", to: "pages#create"

  ### Listings ###
  # todo - make this only accessible to designers

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  patch "/listings/:id", to: "listings#update"
  put "/listings/:id", to: "listings#update"
  post "/listings/new", to: "listings#create", as: "create_listing"
  delete "/listings/:id", to: "listings#destroy"




  ### Quotes ###
  
  #Show quotes (from a given listing)
  get "/quotes", to: "quotes#index", as: "quotes"

  #Show all quotes (from a given user)
  get "/my_quotes", to: "quotes#my_quotes", as: "my_quotes"

  #Make a new quote
  get "/quotes/new", to: "quotes#new", as: "new_quote"
  post "/quotes", to: "quotes#create"

  #View and edit a certain quote
  get "/quotes/:id", to: "quotes#show", as: "quote"
  patch "/quotes/:id", to: "quotes#update"
  put "/quotes/:id", to: "quotes#update"
  get "/quotes/:id/edit", to: "quotes#edit", as: "edit_quote"
  delete "/quotes/:id", to: "quotes#destroy"

  ### Jobs ###

  get "/jobs", to: "jobs#index", as: "jobs"
  get "/jobs/:id", to: "jobs#show", as: "job"
  put "/jobs/:id", to: "jobs#update"
  patch "/jobs/:id", to: "jobs#update"
  post "/jobs/:id", to: "jobs#update"

  ### Stripe payment ###
  post "/payments", to: "payments#stripe"
  get "payments/success", to: "payments#success"

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :printer
  belongs_to :listing

  #We don't need to validate has_job because it defaults to false
  validates :total_price, :job_size, :turnaround_time, presence: true

    #When we create a new job, mark all other

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all

    if current_user.user_type == 'printer'
      @quotes_for_listing = Listing.find(params[:listing]).quotes.where(
        printer_id: Printer.find_by_user_id(current_user.id)
      )
    else
      @quotes_for_listing = Listing.find(params[:listing]).quotes
    end
  end

  def show
    id = params[:id]
    @quote = Quote.find(id)

    stripe_session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      client_reference_id: @quote.id,
      customer_email: @quote.listing.user.email,
      line_items: [{
        name: "Quote id: #{@quote.id}",
        description: @quote.listing.description,
        amount: (@quote.total_price * 100).to_i,
        currency: 'aud',
        quantity: 1
      }],
      success_url: "https://threedirections.herokuapp.com/payments/success?quote_id=#{@quote.id}",
      cancel_url: 'https://threedirections.herokuapp.com/cancel'
    )
    @stripe_session_id = stripe_session.id

    set_quote_arrays
  end

  def create
    if current_user.user_type == 'printer'
      @quote = Quote.create(
        total_price: params[:quote][:total_price],
        job_size: params[:quote][:job_size],
        turnaround_time: params[:quote][:turnaround_time],
        has_job: false,
        printer_id: params[:quote][:printer_id],
        listing_id: params[:quote][:listing_id]
      )

      if @quote.errors.any?
        @listing = params[:quote][:listing_id].to_i
        render :new, listing: @quote[:listing_id]
      else
        redirect_to quote_path(@quote.id)
      end

    end
  end

  def new
    @quote = Quote.new
  end

  def my_quotes
    @user_id = current_user.id
    @quotes = Quote.all

    set_quote_arrays

    #Set total quote amounts so we can display a message if it = 0
    @amount_of_user_quotes = @past_quotes.count + @open_quotes.count
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update(quote_params)
      redirect_to(@quote)
    else
      render "edit"
    end
  end

  def destroy
    Quote.find(params[:id]).destroy

    redirect_to quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(
      :total_price,
      :job_size,
      :turnaround_time,
      :printer_id,
      :listing_id
    )
  end

  def set_quote_arrays
    if current_user.user_type == 'printer'
      @past_quotes = Quote.joins(:printer).where(
        printers: { user_id: current_user.id },
        has_job: true
      )
      @open_quotes = Quote.joins(:printer).where(
        printers: { user_id: current_user.id },
        has_job: false
      )
    elsif current_user.user_type == 'designer'
      @past_quotes = Quote.joins(:listing).where(
        listings: { user_id: current_user.id },
        has_job: true
      )
      @open_quotes = Quote.joins(:listing).where(
        listings: { user_id: current_user.id },
        has_job: false
      )
    else
      redirect_to root_path
    end

    @amount_of_user_quotes = @past_quotes + @open_quotes
  end
end

app/views/quotes/_form.html.erb
<!-- Display any errors with form -->
<% if @quote.errors.any? %>
    <% @quote.errors.full_messages.each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

<div class="listing-form">
    <%= form_with model: quote, local: true do |form| %>
        <!-- If there were previous errors -->
        <%if @listing%>
            <%= form.hidden_field :listing_id, value: @listing %>

        <%elsif params[:listing] != nil%>

            <!-- When there are no errors-->
            <%= form.hidden_field :listing_id, value: params[:listing] %>

        <%else%>

            <!-- When editing an existing quote-->
            <%= form.hidden_field :listing_id, value: @quote[:listing_id] %>

        <%end%>
        <%= form.hidden_field :printer_id, value: Printer.find_by_user_id(current_user.id).id%> 
        <%= form.hidden_field :has_job, value: "0" %>   

        <div class="form-group form-align">

            <%= form.label :total_price %>
            <%= form.number_field :total_price, value: number_to_currency(form.object.total_price.to_f, delimiter: '', unit: ''), step: :any, min: 5, max:99999 %>
        </div>

        <div class="form-group form-align">
            <%= form.label :job_size, "Job Size (in cm³)" %>
            <%= form.number_field :job_size, min:5, max:10000 %>
        </div>

        <div class="form-group form-align">
            <%= form.label :turnaround_time %>
            <%= form.date_field :turnaround_time, min: Date.today %>
        </div>

        <div>
            <%= form.submit class: 'button_link' %>
        </div>
    <% end %>
</div>

app/views/quotes/edit.html.erb
<main class="container-fluid">
    <div class="row">

        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">

            <h1 class="h1 page-header">Edit Quote Id. <%=params[:id]%></h1>

            <%= render "form", quote: @quote %>

        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/quotes/index.html.erb
<main class="container-fluid">
    <div class="row">
    
        <%= render "pages/sidebar" %>

      <!-- start of main content -->
        <div class="col-sm-9">
            <h1 class="h1 page-header">View Quotes for this Listing</h1>

            <%if @quotes_for_listing.count == 0 %>
                
                <%if current_user.user_type == "designer"%>

                    <p class="subtitle">There are no quotes attached to this listing.</p>

                <% else %>
                    <p class="subtitle">You have no quotes attached to this listing.</p>

                <div class="col-md-12 hidden-sm-up">
                    <%= link_to 'Back to Listings', listings_path, class: "button_link" %>
                </div>

                <%end%>
            
            <div class="col-md-12 hidden-sm-up">
                <%= link_to 'Back to Dashboard', dashboard_path, class: "button_link" %>
            </div>

        <%end%>

        <% @quotes_for_listing.each do |quote| %>
                <div class="row card">
                        <div class="col-md-6">
                            <p>Quote Id. <span class="data"><%= quote.id %></span></p>
                            <p>Printer Id. <span class="data"><%= quote.printer_id %></span></p>
                            <p>Total Price: <span class="data">$<%= number_with_precision(quote.total_price, precision: 2) %></span></p>
                        </div>
                        <div class="col-md-3">

                            <!-- Only show edit link for printers --> 
                            <%if current_user.user_type == "printer"%>
                                <%= link_to "Edit Quote", edit_quote_path(quote.id), class: "button_link" %>
                            <%end%>
                                <%= link_to "View Quote",quote_path(quote.id), class: "button_link" %>
                            </div>
                    </div>
        <%end%>



        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/quotes/my_quotes.html.erb
<main class="container-fluid">
    <div class="row">
    
        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">
            <h1 class="h1 page-header"> My Quotes </h1>

            <!-- Display no quotes message -->
            <%if @amount_of_user_quotes == 0%>

                <p class="subtitle">You don't have any quotes at the moment.</p>

            <%end%>

            <h2 class="h2"> Open Quotes </h2>

            <% if @open_quotes.count == 0 %>
                <p class="subtitle">You have no open quotes</p>
            <% end %>
            <!-- if the quote has a job, DO NOT display it here -->
            <%@open_quotes.each do |quote| %>

                <div class="row card">
                    <div class="col-md-6">
                        <% if current_user.user_type == "designer" %>
                            <p>Printer Name: <span class="data"><%= "#{quote.printer.user.first_name} #{quote.printer.user.last_name}" %></span></p>
                        <% else %>
                            <p>Designer Name:<span class="data"><%= "#{quote.listing.user.first_name} #{quote.listing.user.last_name}" %></span></p>
                        <% end %>
                        <p>Quote Id. <span class="data"><%= quote.id %></span></p>
                        <p>Printer Id. <span class="data"><%= quote.printer_id %></span></p>
                        <p>Printer Postcode: <span class="data"><%=quote.printer.user.postcode%></span><p>
                        <p>Total Price: <span class="data">$<%= number_with_precision(quote.total_price, precision: 2) %></span></p>
                    </div>
                    <%if current_user.user_type == "printer"%>                    
                    <div class="col-md-3">
                        <%= link_to "Edit Quote", edit_quote_path(quote.id), class: "button_link" %>
                    </div>
                    <% end %>
                    <div class="col-md-3">
                        <%= link_to "View Quote", quote_path(quote.id), class: "button_link" %>
                    </div>
                    <%@amount_of_user_quotes += 1%>
                </div>

            <%end%>

            <h2 class="h2"> Past Quotes </h2>
            
            <% if @past_quotes.count == 0 %>
                <p class="subtitle">You have no past quotes</p>
            <% end %>
            <!-- if the quote has a job, DO display it here -->
            <%@past_quotes.each do |quote|%>

                <div class="row card">
                    <div class="col-md-6">
                        <% if current_user.user_type == "designer" %>
                            <p>Printer Name: <span class="data"><%= "#{quote.printer.user.first_name} #{quote.printer.user.last_name}" %></span></p>
                        <% else %>
                            <p>Designer Name:<span class="data"><%= "#{quote.listing.user.first_name} #{quote.listing.user.last_name}" %></span></p>
                        <% end %>
                        <p>Quote Id. <span class="data"><%= quote.id %></span></p>
                        <p>Printer Id. <span class="data"><%= quote.printer_id %></span></p>
                        <p>Printer Postcode: <span class="data"><%=quote.printer.user.postcode%></span><p>
                        <p>Total Price: <span class="data">$<%= number_with_precision(quote.total_price, precision: 2) %></span></p>
                    </div>
                    
                    <div class="col-md-3">
                        <%= link_to "View Quote",quote_path(quote.id), class: "button_link" %>
                    </div>
                    <div class="col-md-3">
                        <%= link_to "Go To Job", job_path(Job.find_by_quote_id(quote.id)), class: "button_link"%>
                    </div>
                    
                    <%@amount_of_user_quotes += 1%>
                </div>

            <%end%>

            <div class="col-md-12 hidden-sm-up">
                <%= link_to 'Back to Dashboard', dashboard_path, class: "button_link" %>
            </div>
        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/quotes/new.html.erb
<main class="container-fluid">
    <div class="row">

        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">

            <h1 class="h1 page-header">New Quote for Listing Id. <%=params[:listing]%></h1>

            <%= render "form", quote: @quote, listing: @listing%>

        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/quotes/show.html.erb
<main class="container-fluid">
        <div class="row">
        
            <%= render "pages/sidebar" %>
    
            <!-- start of main content -->
            <div class="col-sm-9">
                <h1 class="h1 page-header"> Quote Id. <%= @quote.id %></h1>

                <div class="row card">
                    <div class="col-md-6">
                        <p>Printer id. <span class="data"><%= @quote.printer_id %></span></p>
                        <p>Printer Postcode: <span class="data"><%=@quote.printer.user.postcode%></span><p>
                        <p>Listing id. <span class="data"><%= @quote.listing_id %></span></p>
                        <p>Total Price: <span class="data">$<%= number_with_precision(@quote.total_price, precision: 2) %></span></p>
                        <p>Job Size (cubic cm): <span class="data"><%= @quote.job_size %></span></p>
                        <p>Turnaround Time: <span class="data"><%= @quote.turnaround_time.to_time.strftime('%A, %d %b %Y') %></span></p>
                    </div>

                    <!-- Only printers can edit quotes -->
                    <%if current_user.user_type == "printer"%>
                        <div class="col-md-3">
                            <% if @quote.has_job == false %>
                                <%= link_to "Edit Quote", edit_quote_path(@quote.id), class: "button_link" %>
                                <%= link_to("Delete Quote", quote_path(@quote.id), class: "button_link", method: :delete, data: { confirm: 'Are you sure you want to delete this quote?' }) %>
                            <%end%>
                        </div>    
                    <% end %>

                    <!-- Check if user is a designer and the job hasn't already been accepted -->
                    <%if current_user.user_type == "designer" and @past_quotes.include?(Quote.find(@quote.id)) == false%>
                        <div class="col-md-3">
                            <button id="stripePayment" class="button_link"> Accept Quote $<%= number_with_precision(@quote.total_price, precision: 2) %></button>
                        </div>    
                    <% end %>

                </div>
                <div class="col-md-3 hidden-xs">
                    <%= link_to 'Back to My Quotes', my_quotes_path, class: "button_link" %>
                </div>
                <%= javascript_include_tag "payment_button" %>
                <div class="col-md-12 hidden-sm-up">
                    <%= link_to 'Back to Listings', listings_path, class: "button_link" %>
                </div>
                <div class="col-md-12 hidden-sm-up">
                    <%= link_to 'Back to My Quotes', my_quotes_path, class: "button_link" %>
                </div>
                <div class="col-md-12 hidden-sm-up">
                    <%= link_to 'Back to Dashboard', dashboard_path, class: "button_link" %>
                </div>
                
        </div>
        <!-- end of main content -->
    </div>
</main>

<script>
    document.getElementById("stripePayment").addEventListener("click", function() {
        var stripe = Stripe('<%= Rails.application.credentials.dig(:stripe, :public) %>');
    
        stripe.redirectToCheckout({
            sessionId: '<%= @stripe_session_id %>',
            }).then(function (result) {
            // If `redirectToCheckout` fails due to a browser or network
            // error, display the localized error message to your customer
            // using `result.error.message`.
        });
    
    });
</script>