config/routes.rb
Rails.application.routes.draw do
  #use custom registrations controller
  devise_for :users, path: "/", path_names: {sign_in: "login", sign_up: "signup"}, controllers: {:registrations => "registrations"}

  root to: "pages#index"
  # get "/", to: "pages#index", as: "root"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  #extra information for printers to enter:
  get "/printer_info", to: "pages#printer_info", as: "printer_info"
  # get "/printers", to: "pages#printers", as: "printers"

  post "/printer_info", to: "pages#create"

  ### Listings ###
  # todo - make this only accessible to designers

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  patch "/listings/:id", to: "listings#update"
  put "/listings/:id", to: "listings#update"
  post "/listings/new", to: "listings#create", as: "create_listing"
  delete "/listings/:id", to: "listings#destroy"




  ### Quotes ###
  
  #Show quotes (from a given listing)
  get "/quotes", to: "quotes#index", as: "quotes"

  #Show all quotes (from a given user)
  get "/my_quotes", to: "quotes#my_quotes", as: "my_quotes"

  #Make a new quote
  get "/quotes/new", to: "quotes#new", as: "new_quote"
  post "/quotes", to: "quotes#create"

  #View and edit a certain quote
  get "/quotes/:id", to: "quotes#show", as: "quote"
  patch "/quotes/:id", to: "quotes#update"
  put "/quotes/:id", to: "quotes#update"
  get "/quotes/:id/edit", to: "quotes#edit", as: "edit_quote"
  delete "/quotes/:id", to: "quotes#destroy"

  ### Jobs ###

  get "/jobs", to: "jobs#index", as: "jobs"
  get "/jobs/:id", to: "jobs#show", as: "job"
  put "/jobs/:id", to: "jobs#update"
  patch "/jobs/:id", to: "jobs#update"
  post "/jobs/:id", to: "jobs#update"

  ### Stripe payment ###
  post "/payments", to: "payments#stripe"
  get "payments/success", to: "payments#success"

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :quotes
  has_one :job
  has_one_attached :design_file
  validates :description, :budget,:due_date, :design_file, presence: true
  validate :file_attached

  private  

  def file_attached
    #add to the errors if the active storage didn't receive a file
    if !design_file.attached?

      errors.add(:design_file, " - please attach a file to be uploaded." )
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:new, :create, :edit, :update]

  def index
    @listings = printer? ? Listing.all : User.find(current_user.id).listings
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.create(listing_params)
    if @listing.errors.any?
      render :new
    else
      redirect_to listing_path(@listing.id)
    end
  end

  def show
    id = params[:id]
    @listing = Listing.find(id)
  end

  def update
    @listing = Listing.find(params[:id])

    if @listing.update(listing_params)
      redirect_to(@listing)
    else
      render :edit
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def destroy
    Listing.find(params[:id]).destroy

    redirect_to listings_path
  end

  private

  def set_listing
    id = params[:id]
    @listing = Listing.find(id)
  end

  def authorize_user
    redirect_to listings_path if printer?
  end

  def listing_params
    params.require(:listing).permit(:description,:budget,:due_date,:has_job,:design_file)
  end

  def printer?
    current_user.user_type == 'printer'
  end
end

app/views/listings/_form.html.erb
<!-- Display any errors with form -->

<% if @listing.errors.any? %>
    <% @listing.errors.full_messages.each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

<div class="listing-form">
    <%= form_with model: listing, local: true do |form| %>
    
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :has_job, value: false %>    
        
        <!--description, budget, due_date, file upload -->
        <div class="form-group form-align">
            <%= form.label :description %>
            <%= form.text_field :description %>
        </div>

        <div class="form-group form-align">
            <% if link_to "New" %>
                <%= form.label :budget %>
                <%= form.number_field :budget, min:5, step: :any %>
            <% else %>
                <%= form.label :budget %>
                <%= form.number_field :budget, min:5, value: number_to_currency(form.object.budget.to_f, delimiter: '', unit: ''), step: :any%>

            <% end %>
        </div>

        <div class="form-group form-align">
            <%= form.label :due_date %>
            <%= form.date_field :due_date, min: Date.today %>
        </div>

        <div class="form-group form-align upload_file">
                <%= form.label :design_file %>
                <%= form.file_field :design_file, accept: "image/png,image/gif,image/jpeg,image/jpg" %>
        </div>

        <div>
            <%= form.submit class: 'button_link' %>
        </div>

    
    <% end %>
</div>

app/views/listings/edit.html.erb
<main class="container-fluid">
    <div class="row">

        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">

            <h1 class="h1 page-header"> Edit Listing Id. <%=params[:id]%></h1>

            <%= render "form", listing: @listing %>
            <div class="col-md-12 hidden-sm-up">
                <a class="button_link" href="<%= listings_path %>">
                        Back to Listings
                </a>
            </div>
            <div class="col-md-12 hidden-sm-up">
                <a class="button_link" href="<%= dashboard_path %>">
                        Back to Dashboard
                </a>
            </div>
        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/listings/index.html.erb
<main class="container-fluid">
    <div class="row">
    
        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">

            <%if current_user.user_type == "designer"%>
                <h1 class="h1 page-header">My Listings</h1>
            <%else%>
                <h1 class="h1 page-header">All Listings</h1>
            <%end%>

            <div class="row">
                <% if current_user.user_type == "designer" %>

                    <!--Display message if there are no listings for the user -->
                    <%if Listing.find_by_user_id(current_user.id) == nil %>
                        <p class="subtitle"> It looks like you don't have any listings currently. </p>
                    <%end%>
                    
                    <div class="col-md-12">
                        <a class="button_link" href="<%= new_listing_path %>">
                            Create New Listing <i class="fas fa-arrow-right"></i>
                        </a>
                    </div> 
                <% end %>
            </div>

            <!-- Display listings if they exist and don't already have a job-->
            <%@listings.each do |listing|%>

            <%if listing.has_job == false%>
                <div class="row card">
                    <div class="col-md-6">
                        <% if current_user.user_type == "printer" %>
                            <p>Designer Name: <span class="data"><%= "#{listing.user.first_name} #{listing.user.last_name}" %></span></p>
                        <%end%>
                        <p>Listing Id. <span class="data"><%=listing.id%></span> </p>
                        <p><span class="data"><%= listing.created_at.to_time.strftime('%A, %d %b %Y') %></span> </p>
                        <p>Description: <span class="data"><%=listing.description%></span> </p>
                    </div>
                    <!-- Only designers can edit listings -->
                    <% if current_user.user_type == "designer" %>
                        <div class="col-md-3">
                            <%= link_to "Edit Listing", edit_listing_path(listing.id), class: "button_link" %>
                        </div>
                    <%end%>
                    <div class="col-md-3">
                        <%= link_to "View Listing", listing_path(listing.id), class: "button_link" %>
                    </div>
                </div>

            <%end%>

                <%# <p>Due date: <%=listing.due_date.to_time.strftime('%A, %d %b %Y')%>
                <%#<p>Created at: <%=listing.created_at.to_time.strftime('%A, %d %b %Y')%> 

            <%end%>
        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/listings/new.html.erb
<main class="container-fluid">
    <div class="row">

        <%= render "pages/sidebar" %>

        <!-- start of main content -->
        <div class="col-sm-9">

            <h1 class="h1 page-header"> New Listing </h1>

            <%= render "form", listing: @listing %>
            <div class="col-md-12 hidden-sm-up">
                <a class="button_link" href="<%= listings_path %>">
                        Back to Listings
                </a>
            </div>
            <div class="col-md-12 hidden-sm-up">
                <a class="button_link" href="<%= dashboard_path %>">
                        Back to Dashboard
                </a>
            </div>

        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/listings/show.html.erb
<main class="container-fluid">
        <div class="row">

                <%= render "pages/sidebar" %>

                <!-- start of main content -->
                <div class="col-sm-9">
                        <h1 class="h1 page-header"> Listing Id. <%= @listing.id %></h1>

                        <div class="row card">
                                <div class="col-md-6">
                                        <p><span class="data"><%= @listing.created_at.to_time.strftime('%A, %d %b %Y') %></span></p>
                                        <p>Description: <span class="data"><%= @listing.description %></span> </p>
                                        <p>Budget: <span class="data">$<%= number_with_precision(@listing.budget, precision: 2) %></span> </p>
                                        <p>Due Date: <span class="data"><%= @listing.due_date.to_time.strftime('%d %b %Y') %></span></p>
                                        <%= image_tag url_for(@listing.design_file), class: "listing_image" if @listing.design_file.attached? %>
                                        <%= link_to "Download #{@listing.design_file.filename}", rails_blob_path(@listing.design_file, disposition: "attachment") if @listing.design_file.attached? %>
                                </div>
                                <% if current_user.user_type == "designer" %>
                                        <div class="col-md-3">
                                                <%= link_to "Edit Listing", edit_listing_path(@listing.id), class: "button_link" %>
                                                <% if @listing.quotes.count == 0 %>
                                                        <%= link_to("Delete Listing", listing_path(@listing.id), class: "button_link", method: :delete, data: { confirm: 'Are you sure you want to delete this listing?' }) %>
                                                <%end%>
                                        </div>
                                <%end%>

                                <%if current_user.user_type == "printer"%>
                                        <div class="col-md-3">
                                                <%= link_to "Create Quote",new_quote_path(listing: @listing.id), class: "button_link" %>
                                        </div>
                                <%end%>
                                
                                <!-- Link to quotes with the amount varying depending on user type --

                                <%if current_user.user_type == "designer"%>

                                        <!-- set quote_count to 0 if there are none, to the total amount if there are some --
                                        <%Quote.find_by_listing_id(@listing.id) == nil? ? quote_count = 0 : quote_count = Quote.where(listing_id: @listing.id).count %>

                                <%else%>
                                        <!-- For printers, only show quotes they have personally made on the listing --
                                        <%Quote.find_by_listing_id(@listing.id) == nil? ? quote_count = 0 : quote_count = Quote.where(listing_id: @listing.id, printer_id: (Printer.find_by_user_id(current_user.id))).count %>
                                <%end%>

                                --
                                <%=link_to "View Quotes (#{quote_count})", quotes_path(listing: @listing)%>
                                -->
                                <div class="col-md-3">
                                        <%= link_to "View Quotes", quotes_path(listing: @listing), class: "button_link" %>
                                </div>
                                
                        </div>
                        <div class="col-md-3 hidden-xs">
                                <%= link_to "Back to Listings", listings_path, class: "button_link" %>       
                        </div>
                        <div class="col-md-12 hidden-sm-up">
                                <%= link_to 'Back to Listings', listings_path, class: "button_link" %>
                        </div>
                        <div class="col-md-12 hidden-sm-up">
                                <%= link_to 'Back to My Quotes', my_quotes_path, class: "button_link" %>
                        </div>
                        <div class="col-md-12 hidden-sm-up">
                                <%= link_to 'Back to Dashboard', dashboard_path, class: "button_link" %>
                        </div>
                </div>
                <!-- end of main content -->
        </div>
</main>