config/routes.rb
Rails.application.routes.draw do
  #use custom registrations controller
  devise_for :users, path: "/", path_names: {sign_in: "login", sign_up: "signup"}, controllers: {:registrations => "registrations"}

  root to: "pages#index"
  # get "/", to: "pages#index", as: "root"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  #extra information for printers to enter:
  get "/printer_info", to: "pages#printer_info", as: "printer_info"
  # get "/printers", to: "pages#printers", as: "printers"

  post "/printer_info", to: "pages#create"

  ### Listings ###
  # todo - make this only accessible to designers

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  patch "/listings/:id", to: "listings#update"
  put "/listings/:id", to: "listings#update"
  post "/listings/new", to: "listings#create", as: "create_listing"
  delete "/listings/:id", to: "listings#destroy"




  ### Quotes ###
  
  #Show quotes (from a given listing)
  get "/quotes", to: "quotes#index", as: "quotes"

  #Show all quotes (from a given user)
  get "/my_quotes", to: "quotes#my_quotes", as: "my_quotes"

  #Make a new quote
  get "/quotes/new", to: "quotes#new", as: "new_quote"
  post "/quotes", to: "quotes#create"

  #View and edit a certain quote
  get "/quotes/:id", to: "quotes#show", as: "quote"
  patch "/quotes/:id", to: "quotes#update"
  put "/quotes/:id", to: "quotes#update"
  get "/quotes/:id/edit", to: "quotes#edit", as: "edit_quote"
  delete "/quotes/:id", to: "quotes#destroy"

  ### Jobs ###

  get "/jobs", to: "jobs#index", as: "jobs"
  get "/jobs/:id", to: "jobs#show", as: "job"
  put "/jobs/:id", to: "jobs#update"
  patch "/jobs/:id", to: "jobs#update"
  post "/jobs/:id", to: "jobs#update"

  ### Stripe payment ###
  post "/payments", to: "payments#stripe"
  get "payments/success", to: "payments#success"

end

app/views/pages/_sidebar.html.erb
<!-- start of sidebar -->
<div class="col-sm-3 hidden-sm-down sidebar">
    <div class="user_avatar">
        <%if current_user.user_type == "designer"%>
            <div class="howItWorks_image">
                <%= image_tag "Designer-Avatar.png", alt: "Designer Avatar", class: "img-responsive img-circle" %>
            </div>
        <% else %>
            <div class="howItWorks_image">
                <%= image_tag "Printer-Avatar.png", alt: "Printer Avatar", class: "img-responsive img-circle" %>
            </div>
        <% end %>
        <h3><%= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}"%></h3>
    </div>
        <ul class="nav nav-pills nav-stacked">
            <li><a href="<%= dashboard_path %>">Dashboard</a></li>
            <% if current_user.user_type == "designer" %>
                <li><a href="<%= listings_path %>">View My Listings</a></li>
            <% else %>
                <li><a href="<%= listings_path %>">View All Listings</a></li>
            <% end %>
            <li><a href="<%= my_quotes_path(@user_id) %>">View My Quotes</a></li>
            <li><a href="<%= jobs_path %>">View My Jobs</a></li>
        </ul>
</div>
<!-- end of sidebar -->

app/views/pages/dashboard.html.erb
<main class="container-fluid">
    <div class="row">

        <%= render "pages/sidebar" %>
        
        <!-- start of main content -->
        <div class="col-sm-9">
            <!-- <%= render "shared/notice" %> -->
            <h1 class="h1 page-header"><%=current_user.user_type.capitalize%> Dashboard</h1>

            <h2><%="Hi, #{current_user.first_name.capitalize}"%></h2>

        
            <!--What the designer sees -->
            
            <%if current_user.user_type == "designer"%>
                <div class="col-md-12">
                    <a class="button_link" href="<%= new_listing_path %>">
                        Create New Listing <i class="fas fa-arrow-right"></i>
                    </a>
                </div>    
                <div class="my_summary">
                    <h3>My Jobs Summary</h3>
                    <div class="row">
                        <div class="col-xs-4 col-sm-4 summary">
                            <a href="<%= listings_path %>">
                                <h3><%= @active_listings %></h3>
                                <% if @active_listings == 1 %>
                                    <p>Listing</p>
                                <% else %>
                                    <p>Listings</p>
                                <% end %>
                            </a>
                        </div>
                        <div class="col-xs-4 col-sm-4 summary">
                            <a href="<%= my_quotes_path(@user_id) %>">
                                <h3><%= @open_quotes %></h3>
                                <% if @open_quotes == 1 %>
                                    <p>Quote</p>
                                <% else %>
                                    <p>Quotes</p>
                                <% end %>
                            </a>
                        </div>
                        <div class="col-xs-4  col-sm-4 summary">

                            <a href="<%= jobs_path %>">
                                <h3><%= @completed_jobs %></h3>
                                <% if @completed_jobs == 1 %>
                                    <p>Completed Job</p>
                                <% else %>
                                    <p>Completed Jobs</p>
                                <% end %>
                            </a>

                        </div>

                    </div>
                </div>
            
            <!--What the printer sees -->
            <%else%>
                <div class="my_summary">
                    <h3>My Jobs Summary</h3>
                    <div class="row">
                        <div class="col-xs-4 col-sm-4 summary">
                            <a href="<%= listings_path %>">
                                <h3><%= @listings_count %></h3>
                                <% if @listings_count == 1 %>
                                    <p>Listing</p>
                                <% else %>
                                    <p>Listings</p>
                                <% end %>
                            </a>
                        </div>
                        <div class="col-xs-4 col-sm-4 summary">
                            <a href="<%= my_quotes_path(@user_id) %>">
                                <h3><%= @open_quotes %></h3>
                                <% if @open_quotes == 1 %>
                                    <p>Quote</p>
                                <% else %>
                                    <p>Quotes</p>
                                <% end %>
                            </a>
                            <!-- Quote.joins(:printer).where(printers: {user_id: @user_id}).count -->
                        </div>
                        <div class="col-xs-4  col-sm-4 summary">
                            <a href="<%= jobs_path %>">
                                <h3><%= @completed_jobs %></h3>
                                <% if @completed_jobs == 1 %>
                                    <p>Completed Job</p>
                                <% else %>
                                    <p>Completed Jobs</p>
                                <% end %>
                            </a>
                        </div>

                    </div>
                </div>
            <%end%>

            <div class="col-md-12 hidden-sm-up">
                <% if current_user.user_type == "designer" %>
                    <a class="button_link" href="<%= listings_path %>">
                        View My Listings <i class="fas fa-arrow-right"></i>
                    </a>
                <% else %>
                    <a class="button_link" href="<%= listings_path %>">
                        View All Listings <i class="fas fa-arrow-right"></i>
                    </a>
                <% end %>
            </div>
            <div class="col-md-12 hidden-sm-up">
                <a class="col-md-12 hidden-sm-up button_link" href="<%= my_quotes_path(@user_id) %>">
                    View My Quotes <i class="fas fa-arrow-right"></i>
                </a>
            </div>
            <div class="col-md-12 hidden-sm-up">
                <a class="button_link" href="<%= jobs_path %>">
                    View My Jobs <i class="fas fa-arrow-right"></i>
                </a>
            </div>
        </div>
        <!-- end of main content -->
    </div>
</main>

app/views/pages/index.html.erb
<main class="main_body container-fluid">
    <!-- Main banner image and buttons -->
    <section class="showcase">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-push-6">
                    <div class=".img-responsive hero_image"></div>
                </div>
                <div class="col-md-6 col-md-pull-6">
                    <div>
                        <h1 class="h1">Connecting Printers &amp; Designers</h1>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 hero_signup">
                            <div>
                                <h2 class="h2">Printer</h2>
                            </div>
                            <div>
                                <p>Find opportunities to use your 3D printer and turn it into your side job.</p>
                            </div>
                            <div>
                                <a class="button_link" href="<%= new_user_registration_path(user_type: "printer") %>">
                                    Sign Up As A <br /> Printer
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-6 hero_signup">
                            <div>
                                <h2 class="h2">Designer</h2>
                            </div>
                            <div>
                                <p>Upload your 3D design and find a reliable printer to bring it to life!</p>
                            </div>
                            <div>
                                <a class="button_link" href="<%= new_user_registration_path(user_type: "designer") %>">
                                    Sign Up As A <br />Designer
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
        
    </section>

    <div role="separator" class="divider col-xs-12"></div>

    <!-- How it works section -->
    <section id="howItWorks" class="mx-auto">
        <h2 class="h2">How It Works</h2>
        <div class="row howItWorks">
            <div class="col-sm-4">
                <div class="howItWorks_image">
                    <%= image_tag "How-It-Works_step1.png", alt: "Step 1", class: "img-responsive img-circle" %>
                </div>
                <div>
                    <p>Upload your design</p>
                    <p>Provide some details and upload your file.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="howItWorks_image">
                    <%= image_tag "How-It-Works_step2.png", alt: "Step 2", class: "img-responsive img-circle" %>
                </div>
                <div>
                    <p>Choose a quote</p>
                    <p>Receive multiple quotes from 3D printers to get your job done.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="howItWorks_image">
                    <%= image_tag "How-It-Works_step3.png", alt: "Step 3", class: "img-responsive img-circle" %>
                </div>
                <div>
                    <p>Get it printed</p>
                    <p>Complete the transaction and bring your design to life!</p>
                </div>
            </div>
        </div>
    </section>

    <!-- What is 3D printing section -->
    <section class="whatIs">
        <div class="row">
            <div class="col-xs-12 col-md-5">
                <h2 class="h2">What is 3D Printing?</h2>
                <p>Ut labore et dolore roipi mana aliqua. Enim adeop minim veeniam nostruklad Ut labore et dolore roipi mana aliqua. Enim adeop minim veeniam nostruklad Ut labore et dolore roipi mana aliqua.</p>
            </div>
            <div class="col-xs-12 col-md-7 video-responsive">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/3LBTkLsjHGQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </section>

    <section>
        <div class="row">
            <div class="col-xs-12 col-sm-6 secondary_signup">
                <a class="btn btn-primary btn-block" href="<%= new_user_registration_path(user_type: "printer") %>">
                    <h3 class="h3">Sign Up As a Printer  <i class="fas fa-arrow-right"></i></h3>
                </a>
            </div>
        
            <div class="col-xs-12 col-sm-6 secondary_signup">
                <a class="btn btn-primary btn-block" href="<%= new_user_registration_path(user_type: "designer") %>">
                    <h3 class="h3">Sign Up As a Designer  <i class="fas fa-arrow-right"></i></h3>
                </a>
            </div>
        </div>
        
    </section>
    
        
</main>

app/views/pages/printer_info.html.erb
<main class="container-fluid">
  <div class="row">
    <%= render "shared/notice" %>
    <%if @printer.errors.any?%>
      
      <% @printer.errors.full_messages.each do |error| %>
        <p>*<%= error %></p>
      <% end %>

    <%end%>

    <h1 class="h1 page-header"> Printer Information</h1>

    <p class="subtitle">Please enter your ABN and printer information.</p>

    <%= form_with model: @printer, url: "/printer_info", local: true do |f| %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="field  form-group">
        <%= f.label :abn %><br />
        <%= f.number_field :abn, autofocus: true %>
      </div>

      <div class="field  form-group">
        <%= f.label :printer_model %><br />
        <%= f.text_field :printer_model, autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "Submit Printer Information", class: 'button_link' %>
      </div>

    <% end %>

  </div>
</main>